filebeat.inputs:
- type: filestream
  id: aks-container-logs
  enabled: true
  paths:
  - /var/log/containers/*.log
  parsers.container.stream: all
  prospectors.scanner.symlinks: true
  processors:
  - add_kubernetes_metadata:
      in_cluster: true
      host: ${NODE_NAME}
      matchers:
      - logs_path:
          logs_path: "/var/log/containers/"
  - include_fields:
      fields:
      - host.name
      - input.type
      - kubernetes.container.name
      - kubernetes.namespace
      - kubernetes.node.name
      - kubernetes.pod.name
      - kubernetes.pod.uid
      - log.file.path
      - log.offset
      - message
      - stream

http.enabled: true
http.port: 5066

output.elasticsearch:
  hosts: ["http://elasticsearch.elk.svc.cluster.local:9200"]

  indices:
  - index: "filebeat_biz_nonprod"
    when.or:
    - equals.kubernetes.container.name: "fedlearner-gateway"
    - equals.kubernetes.container.name: "fedlearner-apm-server"
    - equals.kubernetes.container.name: "fedlearner-web-console-v2"
  - index: "filebeat_nonbiz_nonprod" 
